package GUI;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Win 10
 */
public class Find extends javax.swing.JDialog {

    /**
     * Creates new form Find
     */
    MyNotepad dad;
    int fromIndex=0;
    String subContent="";
    public Find(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.dad=(MyNotepad) parent;
        initComponents();
        rbDown.setSelected(true);
        subContent=dad.txtContent.getText();
        this.setTitle("Find");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfFindContent = new javax.swing.JTextField();
        btnFindNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbMatchCase = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        rbUp = new javax.swing.JRadioButton();
        rbDown = new javax.swing.JRadioButton();
        cbWrapAround = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Find what:");

        btnFindNext.setText("Find Next");
        btnFindNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNextActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        cbMatchCase.setText("Match case");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Direction"));

        buttonGroup1.add(rbUp);
        rbUp.setText("Up");

        buttonGroup1.add(rbDown);
        rbDown.setText("Down");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(rbDown)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbUp)
                    .addComponent(rbDown))
                .addContainerGap())
        );

        cbWrapAround.setText("Wrap around");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbWrapAround)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfFindContent, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbMatchCase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFindNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbMatchCase)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFindContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindNext))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbWrapAround)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNextActionPerformed
        String findWhat=tfFindContent.getText();
        String textDad=dad.txtContent.getText();
        if(!findWhat.isEmpty())
        {
            
            if(rbDown.isSelected())
            {
                if(!cbMatchCase.isSelected())//không phân biệt chữ hao chứ thường
                {
                    findWhat=findWhat.toLowerCase();
                    textDad=textDad.toLowerCase();
                }
                if(cbWrapAround.isSelected()){
                    int pos = textDad.indexOf(findWhat, fromIndex);
                    if (pos > -1) {
                        dad.txtContent.select(pos, pos + findWhat.length());
                        fromIndex = pos + findWhat.length();
                    } else {
                        fromIndex = 0;
                        btnFindNextActionPerformed(evt);
                    }
                }
                else{
                    int pos = textDad.indexOf(findWhat, fromIndex);
                    if (pos > -1) {
                        dad.txtContent.select(pos, pos + findWhat.length());
                        fromIndex = pos + findWhat.length();
                    } else {
                        JOptionPane.showMessageDialog(this, "Can not find "+findWhat);
                    }
                }
            } else if (rbUp.isSelected()) {
                if(!cbMatchCase.isSelected())//không phân biệt chữ hao chứ thường
                {
                    findWhat=findWhat.toLowerCase();
                    textDad=textDad.toLowerCase();
                    subContent=subContent.toLowerCase();
                }
                if(cbWrapAround.isSelected()){
                    int pos = subContent.lastIndexOf(findWhat);
                    if (pos > -1) {
                        dad.txtContent.select(pos, pos + findWhat.length());
                        subContent = textDad.substring(0, pos);
                    } else {
                        subContent = dad.txtContent.getText();
                        btnFindNextActionPerformed(evt);
                    }
                }
                else{
                    int pos = subContent.lastIndexOf(findWhat);
                    if (pos > -1) {
                        dad.txtContent.select(pos, pos + findWhat.length());
                        subContent = textDad.substring(0, pos);
                    } else {
                        JOptionPane.showMessageDialog(this, "Can not find "+findWhat);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnFindNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Find dialog = new Find(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFindNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbMatchCase;
    private javax.swing.JCheckBox cbWrapAround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbDown;
    private javax.swing.JRadioButton rbUp;
    private javax.swing.JTextField tfFindContent;
    // End of variables declaration//GEN-END:variables
}
